let links = `@_a_r_a_p_0_0_
@phiogioma
@majishin4
@emi_r_ma
@_izdj_
@furkanadayolu
@aknur.raiymbekova
@bmw_life_turkey
@erjon_km
@peter_860609
@arazw__hakem
@anette098
@mohammadreza_ahmadi1754
@halitmenl
@always_queen17
@havvabadefatiii
@edwardoouu
@q.uadre__
@shobhit7466
@mikkelklodskov
@andre_rustemeyer
@esdrasssoares
@eddywill_mol
@codywong86
@iblamejordan_98
@lil_strempel
@club_of_alessandro
@nurcan_biter
@____r.erfawn____
@shehannaushad
@tavillaverde
@cristinagaller
@madhan_kumar_9
@ergun_kbk.official
@bdoory14678
@sandramartins30
@michael_walsh1984
@theultraking
@amanriyaazkhan
@king__zahed
@_eddy_saad_5
@aysha_diya21
@h.m.hosseiniii
@cherezovvn
@eddu21m
@arthurseabra
@vicent_91
@mehdi.asg_
@muhammdakbas
@mohammad.vazife_khah
@m_art.03
@pedrosrama21
@naheem._.ak
@________kanji
@rushi.kale1999
@___black___opium___
@monster_shanu
@mduwilliam
@caroline_debs
@dlbrin0
@imperial_m140i
@fanydealba
@osama.a.mahameed
@kavymaiyad
@x.1601.x
@joaonasc2
@kirana_larasati123
@faizanshakeeldurugk
@yams.sama_yams.hyung_
@zekepelaez
@stepanyants
@luisasenjo03
@maddiegaudette12
@alcimar14
@arab7959
@nguyenthinhxike
@abedeenminhazul
@tomas_jeremias10
@nadeemtatla
@luiismoreno1
@kristian.toven
@ahm_448
@bashar.fallah
@devil.kqz
@raph_like
@alejandro_anchundiia
@greteliivamagi
@joker_reborn_22
@e1_a1pydn
@roby_giordano19
@tiagosalteiro
@mohamadst2
@mazyy_r
@wsy8335
@shaka_online
@sandip_kushwaha
@kevin_kopser
@jhonstashow
@krmahalim10
@ashkan_me3
@philipps.siegfried
@meiyirkhankyzy_a
@valeryigorevna98
@stephen.pearson21
@yadavnavneet849
@jason_tauh
@cerncec
@callumblogger
@akirilchuk8
@bauti.leguizamon
@nima.aghayii
@tonyelias1516
@fanydealba
@fanydealba
@lucaslussi
@adil.694
@yaseen_saif_
@anya_prohor
@carlosronald03
@moein_ghorbani_2000
@harrygutsell
@maawa.asif
@dray_isaac
@sisk0_mzire_`.split('\n');

console.log(links[1]);

let doublesCount = 0, doubles = [];

for (let i = 0; i < links.length; i++){
	for (let j = i+1; j < links.length; j++){
		if(links[i] == links[j]){
			doubles.push(links[i]);
			doublesCount++;
		}
	}
}

console.log(doubles, doublesCount);
